set(PACKAGE_VERSION "1.0.0")

if(PACKAGE_VERSION VERSION_LESS "${PACKAGE_FIND_VERSION}")
  set(PACKAGE_VERSION_COMPATIBLE FALSE)
else()
  set(PACKAGE_VERSION_COMPATIBLE TRUE)
endif()

set(PACKAGE_VERSION_EXACT FALSE)